### ISSUE TITLE
Multiple script tags for shower.min.js

### ISSUE THREAD

**Issue by swashata** [wptrainingteam/repo-template#19]
https://github.com/wptrainingteam/repo-template/blob/e3ca288c8ac0c9890ae94e19106b6ceaaa5d4909/slides/index.html#L167-L168

In `slides/index.html` we have multiple `<script>` tag for the `shower.min.js` file.

Since the repository doesn't contain the asset by itself, the first line can be removed.

Right now it is also throwing 404 errors. I will create a PR to fix this.

**Comment by JulieKuehl** [comment]
Hello @swashata! This was meant to be a fallback. The idea is that the second one would be the online source of the latest version of the Training Team's slide files, while the other one would be a local (possibly older) version. But perhaps you are right that only one is needed.
